builds:
  - binary: mubeng
    main: .
    ldflags:
      - -s -w -X github.com/mubeng/mubeng/common.Version=v{{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
  
archives:
  - id: binary
    format: binary