name: Pull Request
on:
  pull_request:
    branches:
      - master
    paths:
      - '**.go'

jobs:
  checks:
    name: "Pull Request Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v6
      - uses: github/codeql-action/init@v3
        with:
          languages: go
      - run: make test
      - run: make build
      - name: "Perform CodeQL Analysis"
        uses: github/codeql-action/analyze@v3