name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: "Pull Request Checks"
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: "Check out code"
        uses: actions/checkout@v3

      - name: "GolangCI-Lint"
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.50

      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: "Run tests"
        run: make test

      - name: "Compile the project"
        run: make build

      - name: "Perform CodeQL Analysis"
        uses: github/codeql-action/analyze@v2