name: Publish to DockerHub
on:
  create:
    tags:
      - v*

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps:
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1.0.1
      
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1.1.1
      
      - name: "Login to DockerHub"
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: "Build and push"
        id: docker_build
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          tags: ${{ github.repository }}:latest
      
      - name: "Image digest"
        run: echo ${{ steps.docker_build.outputs.digest }}