name: Review  
on:
  pull_request:
    branches:
      - dev 

jobs:
  review:
    name: "Code Review"
    runs-on: ubuntu-latest  
    if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.event.head_commit.message, '[skip ci]') == false
    steps:  
      - name: "Check out code"
        uses: actions/checkout@v3 

      - name: "Run sonar-scanner"
        uses: kitabisa/sonarqube-action@v1.1.0
        with: 
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}