name: Review  
on: 
  pull_request:
    branches:
      - master 

jobs:
  review:
    name: "Code Review"
    runs-on: ubuntu-latest  
    steps:  
      - name: "Check out code"
        uses: actions/checkout@master 

      - name: "Run sonar-scanner"
        uses: kitabisa/sonarqube-action@v1.1.0
        with: 
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}

      - name: "Set up Go"
        uses: actions/setup-go@v2
        with: 
          go-version: 1.14

      - name: "Test"
        run: make test